openapi: 3.0.1
info:
  title: Git PR workflow demo
  version: 1.0.0
servers:
- url: https://git-pr-workflow-demo.wiremockapi.cloud
paths:
  /projects/{projectId}/tasks:
    get:
      summary: Get projects by projectId tasks.
      operationId: getProjectsByProjectIdTasks
      parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: List tasks in project
          content:
            application/json:
              examples:
                List tasks in project:
                  value: |
                    {
                      "tasks": [
                        {
                          "id": 12345,
                          "title": "chore: refactor task manager",
                          "description": "Factor out the repeated workflow elements to reduce duplication"
                          "labelIds": [53, 67]
                        }
                      ]
                    }
