openapi: 3.0.1
info:
  title: Git PR workflow demo
  description: My test API
  version: 1.0.0
servers:
- url: https://1mlq9.wiremockapi.cloud
paths:
  /projects/{projectId}/tasks:
    get:
      summary: Get projects by projectId tasks.
      description: Get projects by projectId tasks.
      operationId: getProjectsByProjectIdTasks
      parameters:
      - name: projectId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 'Get projects by projectId tasks. - List tasks in project'
          content:
            application/json:
              examples:
                List tasks in project:
                  value: |
                    {
                      "tasks": [
                        {
                          "id": 12345,
                          "title": "Chore: refactor task manager",
                          "description": "Factor out the repeated workflow elements to reduce duplication"
                          "labelIds": [53, 67]
                        }
                      ]
                    }
                Get projects by projectId tasks. - List tasks in project:
                  value: |
                    {
                      "tasks": [
                        {
                          "id": 12345,
                          "title": "Chore: refactor the task manager module",
                          "description": "Factor out the repeated workflow elements to reduce duplication"
                          "labelIds": [53, 67]
                        }
                      ]
                    }
