name: Deploy to WireMock Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install WireMock CLI
      run: npm install -g @wiremock/cli
        
    - name: Set the API token
      run: wiremock config set api_token ${{ secrets.WIREMOCK_TOKEN }}
        
    - name: Push mock API to WireMock Cloud
      run: wiremock push mock-api git-pr-workflow-demo --to 8vo14